definiciones = {
    "¿Qué animal tiene las cinco vocales?": "murcielago",
    "Canto en la orilla, vivo en el agua, no soy pescado, ni soy cigarra.": "rana",
    "En lo alto vive, en lo alto mora, en lo alto teje la tejedora.": "araña",
    "Soy pequeño y blandito y mi casa llevo sobre el lomito.": "caracol",
    "Mi tía Cuca tiene una mala racha, ¿quién será esta muchacha?": "cucaracha",
    "¿Quién será que de noche sale y de día se va?": "buho",
    "Por qué tengo sangre fría aparezco en primavera en piedras encaramada siempre al sol que más calienta.": "serpiente",
    "¿Cuál es el animal que más tarda en quitarse los zapatos?": "cienpies",
    "Dos pinzas tengo, hacia atrás camino, en el agua vivo, en el mar o en el río.": "cangrejo",
    "Tengo hipo al decir mi nombre, ¿quien soy?": "hipopotamo",
    "Verde como el campo, aunque no lo sea. Tampoco es persona, pero habla de veras": "loro",
    "Soy CAN pero no soy perro duro. Si vamos de compras llevo bolsa seGURO": "canguro",
    "Soy roja con pintitas negras. Podrás encontrarme entre las hierbas": "mariquita",
    "Tengo alas de mil colores. Volando y volando me pierdo entre las flores": "mariposa",
    "Me gusta surcar los mares y nadar entre sirenas. Aunque no coma mucho siempre parezco llena": "ballena",
    "En el desierto nací y con arena me he criado. Entre amigos suelen llamarme el jorobado": "camello",
    "Viajo entre las flores. Vivo en la colmena. Fabrico rica miel y una fantástica cera": "abeja",
    "Cuando me acuesto y cuando me levanto. Te acabo de revelar mi canto": "pato",
    "Me gusta ir elegante y con frac. Me encanta nadar pero no volar": "pinguino",
    "Tengo orejas largas y un rabo cortito. Corro y salto muy ligerito": "conejo",
    "Por qué tengo sangre fría, aparezco en primavera, en piedras encaramada siempre al sol que más calienta": "lagartija",
    "El rey de la selva es. Si lo nombras al revés de apellido es Noel": "leon",
    "No me llamo Leonardo, aunque sí me llamo Leo y me apellido Pardo": "leopardo",
    "Soy muy lenta y me gusta nadar. Llevo siempre conmigo el hogar": "tortuga",
    "Tengo manchas y un largo cuello. Soy casi tan alta como el mismo cielo": "jirafa",
    "No es una cama ni un león. Puede esconderse por cualquier rincón": "camaleon",
    "Choco me dice la gente, late mi corazón. El que no sepa mi nombre, es un gran tontorrón.": "chocolate",
    "Zorra le dicen, aunque siempre del revés. Se lo come el japonés y plato muy rico es.": "arroz",
    "Blanca por dentro, verde por fuera. Si quieres que te lo diga, espera.": "pera",
    "Con tomate y con lechuga, en el plato suelo estar; puedo ser algo picante y a muchos hago llorar.": "cebolla",
    "¿Quieres té? ¡Pues toma té! ¿Sabes ya qué fruto es?": "tomate",
    "Vengo de padres cantores, pero yo no soy cantor. Llevo la ropa blanca y amarillo el corazón. ¿Quién soy?": "huevo",
    "La A, anda. La B, besa. La C, reza ¿Qué fruta es esa?": "cereza",
    "Sobre la baca la o. ¿A qué no lo aciertas?": "bacalao",
    "Redondo como la luna y blanco como la cal. Me hacen de leche… ¡y ya no te digo más!": "queso",
    "Oro parece y plata no es, ¡y no lo adivinas de aquí a un mes!": "banana",
    "Aunque no es un hombre, lleva sombrero y al cesar la lluvia sale el primero.": "champiñon",
    "En blanco pañal nací, En verde me transformé, Y durante el crecimiento, Amarillo me quedé.": "limon",
    "Soy una loca amarrada que sólo sirvo para ensalada.": "lechuga",
    "Una señorita va por el mercado con su cola verde y su traje morado.": "berenjena",
    "Somos bolitas redondas que al morir nos despedazan, nos reducen al pellejo y todo el jugo nos sacan.": "uvas",
    "Primero blanca nací, después verde me quedé, y cuando dorada torné, hiciste un jugo de mí.": "naranja",
    "Sombrero sobre sombrero de un arrugado paño. Si no lo adivinas ya, no lo harás en todo el año.": "repollo",
    "Tiene ojos y no ve, tiene agua y no la bebe, tiene carne y no la come tiene barba y no es un hombre.": "coco",
    "Verde fue mi nacimiento y de luto me vestí; los palos me atormentaron y oro fino me volví.": "aceituna",
    "Soy un viejo arrugadito que si me echan al agua salgo mucho más gordito.": "garbanzo",
    "Colada puedo estar y también troceada. A veces me cuelo en la pizza Hawaiana": "anana",
    "Soy un arbolito verde y chiquitito. También soy sanote y el hambre quito": "brocoli",
    "Tengo pepitas negras en mi barriga. En verano te refresco por la noche y por el día": "sandia",
    "Rimo con campana, y con mis variados sabores alegro tu semana": "manzana",
    "Zumba que te zumba, se oye mi son, en las noches navideñas, hasta que aparece el sol": "zambomba",
    "En una larga aberturatengo yo mi dentadura y luego que empiezo a hablar, todas mis piezas se mueven sin poderlas yo parar.": "piano",
    "Con qué instrumento de percusión representa Camille Saint-Saens a los esqueletos en Fósiles": "xilofono",
}


colores = [
    (255, 255, 255),
    (255, 0, 0),
    (0, 255, 0),
    (0, 0, 255),
    (255, 255, 0),
    (0, 255, 255),
    (255, 0, 255),
    (200, 100, 0),
    (0, 156, 140),
    (119, 158, 203),
    (255, 105, 97),
    (253, 253, 150),
]
